import { useState, useEffect, useRef, useCallback } from "react";
import { useNavigate, Link } from "react-router-dom";
import {
  clearAuthSession,
  createTeam,
  getStoredAuthToken,
  getTeams,
  hasStoredAuthSession,
  searchMessages,
  type SearchMessageItem,
} from "../api/client";
import { PageShell, GlassCard, Button, Input, Badge, PageLoading } from "../components/index.js";

interface Team {
  id: string;
  name: string;
  slug: string;
  created_at: string;
}

const teamSlugPattern = /^[a-z0-9]+(?:-[a-z0-9]+)*$/u;

export function DashboardPage() {
  const [teams, setTeams] = useState<Team[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [newTeamName, setNewTeamName] = useState("");
  const [newTeamSlug, setNewTeamSlug] = useState("");
  const [creating, setCreating] = useState(false);
  const [createError, setCreateError] = useState<string | null>(null);
  const slugAutoGenerated = useRef(false);

  const [searchQuery, setSearchQuery] = useState("");
  const [selectedTeamId, setSelectedTeamId] = useState("");
  const [searchResults, setSearchResults] = useState<SearchMessageItem[]>([]);
  const [searching, setSearching] = useState(false);
  const [searchError, setSearchError] = useState<string | null>(null);
  const [searchTotal, setSearchTotal] = useState(0);
  const [hasSearched, setHasSearched] = useState(false);

  const navigate = useNavigate();

  useEffect(() => {
    if (!hasStoredAuthSession()) {
      navigate("/login");
      return;
    }

    void fetchTeams();
  }, [navigate]);

  const fetchTeams = async () => {
    try {
      setLoading(true);
      setError(null);
      const token = getStoredAuthToken();
      if (!token) throw new Error("未找到登录凭据");

      const data = await getTeams(token);
      setTeams(data.data || []);
    } catch (err: any) {
      if (err.message === "UNAUTHORIZED" || err.message?.includes("401")) {
        clearAuthSession();
        navigate("/login");
        return;
      }

      setError(err.message || "获取团队列表失败");
    } finally {
      setLoading(false);
    }
  };

  const generateSlug = useCallback((name: string): string => {
    return name
      .normalize("NFKD")
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/-+/g, "-")
      .replace(/^-|-$/g, "");
  }, []);

  const handleNameChange = (value: string) => {
    setNewTeamName(value);
    const generated = generateSlug(value);

    if (slugAutoGenerated.current) {
      setNewTeamSlug(generated);
      return;
    }

    if (newTeamSlug === "") {
      setNewTeamSlug(generated);
      slugAutoGenerated.current = generated !== "";
    }
  };

  const handleSlugChange = (value: string) => {
    const normalized = generateSlug(value);
    setNewTeamSlug(normalized);
    slugAutoGenerated.current = false;
  };

  const handleCreateTeam = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!newTeamName.trim() || !newTeamSlug.trim()) {
      setCreateError("名称和标识不能为空");
      return;
    }
    if (!teamSlugPattern.test(newTeamSlug.trim())) {
      setCreateError("团队标识只支持小写字母、数字和连字符");
      return;
    }

    try {
      setCreating(true);
      setCreateError(null);
      const token = getStoredAuthToken();
      if (!token) throw new Error("未找到登录凭据");

      await createTeam(token, {
        name: newTeamName.trim(),
        slug: newTeamSlug.trim(),
      });

      setNewTeamName("");
      setNewTeamSlug("");
      await fetchTeams();
    } catch (err: any) {
      setCreateError(err.message || "创建团队失败");
    } finally {
      setCreating(false);
    }
  };

  const handleLogout = () => {
    clearAuthSession();
    navigate("/login");
  };

  const handleSearch = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!searchQuery.trim() || !selectedTeamId) {
      setSearchError("请输入关键词并选择团队");
      return;
    }

    try {
      setSearching(true);
      setHasSearched(true);
      setSearchError(null);
      setSearchResults([]);
      setSearchTotal(0);
      const token = getStoredAuthToken();
      if (!token) throw new Error("未找到登录凭据");

      const response = await searchMessages(token, selectedTeamId, searchQuery.trim());
      setSearchResults(response.data || []);
      setSearchTotal(response.meta?.total ?? 0);
    } catch (err: any) {
      if (err.message?.includes("401") || err.message === "UNAUTHORIZED") {
        clearAuthSession();
        navigate("/login");
        return;
      }

      setSearchError(err.message || "搜索失败");
    } finally {
      setSearching(false);
    }
  };

  const getSearchResultLabel = (item: SearchMessageItem) => {
    if (item.result_type === "message") {
      return item.sender_type === "member" ? "成员消息" : "助手回复";
    }

    switch (item.event_type) {
      case "command.summary":
        return "命令摘要";
      case "status.changed":
        return "状态变更";
      case "session.shared":
      case "session.privatized":
        return "可见性变更";
      case "message.failed":
        return "失败记录";
      case "message.queued":
        return "排队记录";
      default:
        return "会话事件";
    }
  };

  const getSearchResultVariant = (item: SearchMessageItem) => {
    if (item.result_type === "message") {
      return item.sender_type === "member" ? "default" : "accent";
    }

    if (item.event_type === "message.failed") {
      return "danger";
    }

    if (
      item.event_type === "status.changed"
      || item.event_type === "session.shared"
      || item.event_type === "session.privatized"
    ) {
      return "warning";
    }

    return "success";
  };

  if (loading) return <PageLoading label="加载团队中..." />;

  return (
    <PageShell
      title="仪表盘"
      actions={(
        <Button variant="ghost" size="sm" onClick={handleLogout}>
          退出登录
        </Button>
      )}
    >
      <GlassCard className="mb-6">
        <h2 className="text-lg font-semibold text-text-primary mb-4">搜索消息</h2>
        <form onSubmit={handleSearch} className="flex flex-col gap-3">
          {searchError && (
            <div className="px-3 py-2 rounded-md bg-danger-muted border border-danger/30 text-sm text-danger">
              {searchError}
            </div>
          )}
          <div className="flex flex-col sm:flex-row gap-3">
            <Input
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              placeholder="输入关键词搜索..."
              className="flex-1"
            />
            <select
              value={selectedTeamId}
              onChange={(e) => setSelectedTeamId(e.target.value)}
              className="w-full sm:w-48 px-3.5 py-2.5 rounded-button bg-surface-2 border border-glass-border text-text-primary text-sm focus:outline-none focus:border-accent/50 focus:ring-2 focus:ring-accent/20"
            >
              <option value="">选择团队</option>
              {teams.map((team) => (
                <option key={team.id} value={team.id}>{team.name}</option>
              ))}
            </select>
            <Button type="submit" loading={searching} className="shrink-0">
              搜索
            </Button>
          </div>
          <p className="text-xs text-text-muted">
            支持搜索成员消息、助手最终回复，以及命令摘要、状态变更等会话摘要内容。
          </p>
        </form>

        {searchResults.length > 0 && (
          <div className="mt-4 animate-fade-in">
            <p className="text-sm text-text-muted mb-3">
              找到 <strong className="text-text-primary">{searchTotal}</strong> 条结果
            </p>
            <div className="flex flex-col gap-2">
              {searchResults.map((item) => (
                <Link
                  key={item.event_id ?? item.message_id ?? `${item.session_id}-${item.created_at}`}
                  to={`/sessions/${item.session_id}`}
                  state={{ backTo: { label: "返回仪表盘", href: "/dashboard" } }}
                  className="block"
                >
                  <div className="p-3 rounded-lg bg-surface-2 border border-glass-border hover:border-accent/30 hover:bg-glass-hover transition-all duration-200">
                    <div className="flex flex-wrap items-center gap-2 mb-2">
                      <Badge variant="accent">{item.project_name}</Badge>
                      <Badge variant={getSearchResultVariant(item)}>
                        {getSearchResultLabel(item)}
                      </Badge>
                      <span className="text-xs text-text-muted truncate">
                        {item.session_title}
                      </span>
                    </div>
                    <p className="text-sm text-text-primary whitespace-pre-wrap break-words line-clamp-3">
                      {item.preview || item.content}
                    </p>
                    <div className="mt-2 flex items-center justify-between gap-3 text-xs text-text-muted">
                      <span className="truncate">点击可进入对应会话</span>
                      <span>{new Date(item.occurred_at || item.created_at).toLocaleString()}</span>
                    </div>
                  </div>
                </Link>
              ))}
            </div>
          </div>
        )}

        {hasSearched && !searching && !searchError && searchResults.length === 0 && (
          <div className="mt-4 rounded-lg border border-dashed border-glass-border bg-surface-2/60 px-4 py-6 text-sm text-text-muted">
            没有找到相关结果。可以试试更短的关键词，或者切换团队后再搜索。
          </div>
        )}
      </GlassCard>

      <GlassCard className="mb-6">
        <h2 className="text-lg font-semibold text-text-primary mb-4">我的团队</h2>
        {error && (
          <div className="px-3 py-2 rounded-md bg-danger-muted border border-danger/30 text-sm text-danger mb-4">
            {error}
          </div>
        )}
        {teams.length === 0 ? (
          <p className="text-sm text-text-muted">还没有团队，在下方创建一个吧。</p>
        ) : (
          <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
            {teams.map((team) => (
              <Link
                key={team.id}
                to={`/teams/${team.id}`}
                state={{ backTo: { label: "返回仪表盘", href: "/dashboard" } }}
                className="block"
              >
                <div className="p-4 rounded-lg bg-surface-2 border border-glass-border hover:border-accent/30 hover:bg-glass-hover transition-all duration-200 group">
                  <h3 className="font-semibold text-text-primary group-hover:text-accent-light transition-colors">
                    {team.name}
                  </h3>
                  <p className="text-xs text-text-muted mt-1">@{team.slug}</p>
                  <p className="text-xs text-text-muted mt-2">
                    {new Date(team.created_at).toLocaleDateString()}
                  </p>
                </div>
              </Link>
            ))}
          </div>
        )}
      </GlassCard>

      <GlassCard>
        <h2 className="text-lg font-semibold text-text-primary mb-4">创建团队</h2>
        <form onSubmit={handleCreateTeam} className="flex flex-col gap-3">
          {createError && (
            <div className="px-3 py-2 rounded-md bg-danger-muted border border-danger/30 text-sm text-danger">
              {createError}
            </div>
          )}
          <div className="grid gap-3 sm:grid-cols-[minmax(0,1fr)_minmax(0,1fr)_auto]">
            <div className="min-w-0">
              <Input
                value={newTeamName}
                onChange={(e) => handleNameChange(e.target.value)}
                placeholder="团队名称"
                className="w-full"
                required
              />
            </div>
            <div className="min-w-0">
              <Input
                value={newTeamSlug}
                onChange={(e) => handleSlugChange(e.target.value)}
                placeholder="团队标识（小写字母、数字、连字符，例如 my-team）"
                className="w-full"
                required
              />
              <p className="mt-1 text-xs text-text-muted">
                中文名称不会原样同步到团队标识；这里请填写英文、数字或连字符。
              </p>
            </div>
            <Button type="submit" loading={creating} className="shrink-0">
              创建团队
            </Button>
          </div>
        </form>
      </GlassCard>
    </PageShell>
  );
}
