import { useState, useEffect, useRef, useCallback } from "react";
import { useNavigate, Link } from "react-router-dom";
import { getTeams, createTeam, searchMessages, type SearchMessageItem } from "../api/client";
import { PageShell, GlassCard, Button, Input, Badge, PageLoading } from "../components/index.js";

interface Team {
  id: string;
  name: string;
  slug: string;
  created_at: string;
}

export function DashboardPage() {
  const [teams, setTeams] = useState<Team[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [newTeamName, setNewTeamName] = useState("");
  const [newTeamSlug, setNewTeamSlug] = useState("");
  const [creating, setCreating] = useState(false);
  const [createError, setCreateError] = useState<string | null>(null);
  const slugAutoGenerated = useRef(false);

  // Search state
  const [searchQuery, setSearchQuery] = useState("");
  const [selectedTeamId, setSelectedTeamId] = useState("");
  const [searchResults, setSearchResults] = useState<SearchMessageItem[]>([]);
  const [searching, setSearching] = useState(false);
  const [searchError, setSearchError] = useState<string | null>(null);
  const [searchTotal, setSearchTotal] = useState(0);

  const navigate = useNavigate();

  useEffect(() => {
    const token = localStorage.getItem("token");
    if (!token) {
      navigate("/login");
      return;
    }
    fetchTeams();
  }, [navigate]);

  const fetchTeams = async () => {
    try {
      setLoading(true);
      setError(null);
      const token = localStorage.getItem("token");
      if (!token) throw new Error("未找到登录凭据");

      const data = await getTeams(token);
      setTeams(data.data || []);
    } catch (err: any) {
      if (err.message === "UNAUTHORIZED" || err.message?.includes("401")) {
        localStorage.removeItem("token"); navigate("/login"); return;
      }
      setError(err.message || "获取团队列表失败");
    } finally {
      setLoading(false);
    }
  };

  const generateSlug = useCallback((name: string): string => {
    return name
      .toLowerCase()
      .replace(/[^a-z0-9\u4e00-\u9fff-]/g, "-")
      .replace(/-+/g, "-")
      .replace(/^-|-$/g, "");
  }, []);

  const handleNameChange = (value: string) => {
    setNewTeamName(value);
    if (slugAutoGenerated.current) {
      setNewTeamSlug(generateSlug(value));
    } else if (newTeamSlug === "") {
      const generated = generateSlug(value);
      if (generated) {
        setNewTeamSlug(generated);
        slugAutoGenerated.current = true;
      }
    }
  };

  const handleSlugChange = (value: string) => {
    setNewTeamSlug(value);
    slugAutoGenerated.current = false;
  };

  const handleCreateTeam = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!newTeamName.trim() || !newTeamSlug.trim()) {
      setCreateError("名称和标识不能为空");
      return;
    }
    try {
      setCreating(true);
      setCreateError(null);
      const token = localStorage.getItem("token");
      if (!token) throw new Error("未找到登录凭据");

      await createTeam(token, { name: newTeamName.trim(), slug: newTeamSlug.trim() });

      setNewTeamName("");
      setNewTeamSlug("");
      await fetchTeams();
    } catch (err: any) {
      setCreateError(err.message || "创建团队失败");
    } finally {
      setCreating(false);
    }
  };

  const handleLogout = () => {
    localStorage.removeItem("token");
    navigate("/login");
  };

  const handleSearch = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!searchQuery.trim() || !selectedTeamId) {
      setSearchError("Enter a keyword and select a team");
      return;
    }
    try {
      setSearching(true);
      setSearchError(null);
      setSearchResults([]);
      setSearchTotal(0);
      const token = localStorage.getItem("token");
      if (!token) throw new Error("No authentication token found");

      const response = await searchMessages(token, selectedTeamId, searchQuery.trim());
      setSearchResults(response.data || []);
      setSearchTotal(response.meta?.total ?? 0);
    } catch (err: any) {
      if (err.message?.includes("401") || err.message === "UNAUTHORIZED") {
        localStorage.removeItem("token"); navigate("/login"); return;
      }
      setSearchError(err.message || "Search failed");
    } finally {
      setSearching(false);
    }
  };

  if (loading) return <PageLoading label="Loading teams..." />;

  return (
    <PageShell
      title="Dashboard"
      actions={
        <Button variant="ghost" size="sm" onClick={handleLogout}>
          退出登录
        </Button>
      }
    >
      {/* Search Section */}
      <GlassCard className="mb-6">
        <h2 className="text-lg font-semibold text-text-primary mb-4">搜索消息</h2>
        <form onSubmit={handleSearch} className="flex flex-col gap-3">
          {searchError && (
            <div className="px-3 py-2 rounded-md bg-danger-muted border border-danger/30 text-sm text-danger">
              {searchError}
            </div>
          )}
          <div className="flex flex-col sm:flex-row gap-3">
            <Input
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              placeholder="输入关键词搜索..."
              className="flex-1"
            />
            <select
              value={selectedTeamId}
              onChange={(e) => setSelectedTeamId(e.target.value)}
              className="w-full sm:w-48 px-3.5 py-2.5 rounded-button bg-surface-2 border border-glass-border text-text-primary text-sm focus:outline-none focus:border-accent/50 focus:ring-2 focus:ring-accent/20"
            >
              <option value="">选择团队</option>
              {teams.map((team) => (
                <option key={team.id} value={team.id}>{team.name}</option>
              ))}
            </select>
            <Button type="submit" loading={searching} className="shrink-0">
              搜索
            </Button>
          </div>
        </form>

        {searchResults.length > 0 && (
          <div className="mt-4 animate-fade-in">
            <p className="text-sm text-text-muted mb-3">
              找到 <strong className="text-text-primary">{searchTotal}</strong> 条结果
            </p>
            <div className="flex flex-col gap-2">
              {searchResults.map((item) => (
                <div
                  key={item.message_id}
                  className="p-3 rounded-lg bg-surface-2 border border-glass-border"
                >
                  <div className="flex items-center gap-2 mb-1">
                    <Badge variant="accent">{item.project_name}</Badge>
                    <span className="text-xs text-text-muted">{item.session_title}</span>
                  </div>
                  <p className="text-sm text-text-primary whitespace-pre-wrap break-words line-clamp-3">
                    {item.content.length > 200 ? item.content.slice(0, 200) + "..." : item.content}
                  </p>
                  <p className="text-xs text-text-muted mt-1">
                    {new Date(item.created_at).toLocaleString()}
                  </p>
                </div>
              ))}
            </div>
          </div>
        )}
      </GlassCard>

      {/* Teams Section */}
      <GlassCard className="mb-6">
        <h2 className="text-lg font-semibold text-text-primary mb-4">我的团队</h2>
        {error && (
          <div className="px-3 py-2 rounded-md bg-danger-muted border border-danger/30 text-sm text-danger mb-4">
            {error}
          </div>
        )}
        {teams.length === 0 ? (
          <p className="text-sm text-text-muted">还没有团队，在下方创建一个吧。</p>
        ) : (
          <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
            {teams.map((team) => (
              <Link key={team.id} to={`/teams/${team.id}`} className="block">
                <div className="p-4 rounded-lg bg-surface-2 border border-glass-border hover:border-accent/30 hover:bg-glass-hover transition-all duration-200 group">
                  <h3 className="font-semibold text-text-primary group-hover:text-accent-light transition-colors">
                    {team.name}
                  </h3>
                  <p className="text-xs text-text-muted mt-1">@{team.slug}</p>
                  <p className="text-xs text-text-muted mt-2">
                    {new Date(team.created_at).toLocaleDateString()}
                  </p>
                </div>
              </Link>
            ))}
          </div>
        )}
      </GlassCard>

      {/* Create Team Section */}
      <GlassCard>
        <h2 className="text-lg font-semibold text-text-primary mb-4">创建团队</h2>
        <form onSubmit={handleCreateTeam} className="flex flex-col gap-3">
          {createError && (
            <div className="px-3 py-2 rounded-md bg-danger-muted border border-danger/30 text-sm text-danger">
              {createError}
            </div>
          )}
          <div className="flex flex-col sm:flex-row gap-3">
            <Input
              value={newTeamName}
              onChange={(e) => handleNameChange(e.target.value)}
              placeholder="团队名称"
              className="flex-1"
              required
            />
            <Input
              value={newTeamSlug}
              onChange={(e) => handleSlugChange(e.target.value)}
              placeholder="团队标识（小写字母+数字+连字符，如 my-team）"
              className="flex-1"
              required
            />
            <Button type="submit" loading={creating} className="shrink-0">
              创建团队
            </Button>
          </div>
        </form>
      </GlassCard>
    </PageShell>
  );
}
